# <h1 align='center' >Computer Application in Engineering Design Lab</h1>
<h2 align='center' >Lab 12, BCE Fall 2021</h2>
<h3 align='left' >Instructor: Muhammad Farooq Khan</h3>
<h4>Date: 13-Dec-2021</h4>

### Numpy

In [1]:
import numpy as np # imports a fast numerical programming library

In [2]:
x = np.array([1,2,3])     #1d array
print(x)

[1 2 3]


In [3]:
x = np.array([[1,2,3],[4,5,6]])    #2d array
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [4]:
x = np.arange(0,10,0.5)
print(x)
x.shape   # shape should have been (20,1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


(20,)

In [5]:
# .shape[0] gives rows which is 20 above
# .shape[1] gives columns


x = x.reshape(x.shape[0],1)   # solve the above issue
x.shape    

(20, 1)

In [6]:
x = np.linspace(0,2,9)    #Add evenly spaced values btw interval to array of length
print(x)
x.shape

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


(9,)

In [7]:
x = np.linspace(0,2,9).reshape(9,1)    #can directly solve the dimension issue
x.shape

(9, 1)

In [8]:
# by default numpy stores float values check the output

x = np.zeros((1,2))    
print(x)
x.shape

[[0. 0.]]


(1, 2)

In [9]:
# lets make the numpy array of integer zeros

x = np.zeros((1,2), dtype = int)    
print(x)
x.shape

[[0 0]]


(1, 2)

In [10]:
# Creates random array of specified dimensions 

x = np.random.random((5,5))
print(x)
x.shape

[[0.14703104 0.83628032 0.60617322 0.50920102 0.8822448 ]
 [0.34749602 0.18419787 0.06943319 0.22150591 0.8086058 ]
 [0.65811918 0.42867931 0.66603412 0.89158926 0.41300885]
 [0.76394703 0.50050163 0.4949355  0.24839298 0.71107276]
 [0.93000557 0.31730975 0.52812487 0.25065313 0.25423794]]


(5, 5)

In [11]:
# Creates an empty array of specified dimensions

x = np.empty((2,2), dtype = int)
print(x)
x.shape

[[0 0]
 [0 0]]


(2, 2)

In [12]:
x = np.empty((2,2), dtype = int)
print(x)
x.shape

[[0 0]
 [0 0]]


(2, 2)

In [13]:
# it finds the lentgh of array
x = np.array([1,3,6])
len(x) 

3

In [14]:
x = np.array([[1,3,6]])
len(x)   
# notice the change for 2D array, it count the number of rows

1

In [15]:
# lentgh is important when you dont know the size of vector and you want to use for loop on a complete array
# so we use len(x) as an for loop upper limit

In [16]:
x = np.zeros((1,2)) # float type array
print(x)
x = x.astype(int)    # convert to int
print(x)

[[0. 0.]]
[[0 0]]


In [17]:
# Creates copy of array
x = np.array([[1,2,3],[4,5,6]])
y = np.copy(x)
print(y)

[[1 2 3]
 [4 5 6]]


In [18]:
x = np.array([1,2,3])
x = np.append(x,5)
print(x)

[1 2 3 5]


In [19]:
x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6]])
x = np.append(x,y)
print(x)
x.shape

[1 2 3 1 2 3 4 5 6]


(9,)

In [20]:
y = x.reshape(1,x.shape[0])    
print(y)
y.shape

[[1 2 3 1 2 3 4 5 6]]


(1, 9)

In [21]:
print(y)
y = np.delete(y,3,axis=1)   # delete 3rd index or 4th value
print(y)

[[1 2 3 1 2 3 4 5 6]]
[[1 2 3 2 3 4 5 6]]


In [22]:
# concatenating 2D arrays with only 2D and 1D array with only 1D array

x = np.array([[1,2,3]])
y = np.array([[1,2,3],[4,5,6]])
print(x)
print(" ")
print(y)
print(" ")
z = np.concatenate((x,y),axis=0)
print(z)

[[1 2 3]]
 
[[1 2 3]
 [4 5 6]]
 
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [23]:
# stack arrays vertically, remember number of columns should be same

x = np.array([[1,5,3]])
y = np.array([[1,2,3],[4,5,6]])
print(x)
print(" ")
print(y)
print(" ")
z = np.vstack((x,y))
print(z)

[[1 5 3]]
 
[[1 2 3]
 [4 5 6]]
 
[[1 5 3]
 [1 2 3]
 [4 5 6]]


In [24]:
# stack arrays horizontally, remember number of rows should be same

x = np.array([[1,5,3],[4,7,0]])
y = np.array([[9,2,3],[4,5,6]])
print(x)
print(" ")
print(y)
print(" ")
z = np.hstack((x,y))
print(z)

[[1 5 3]
 [4 7 0]]
 
[[9 2 3]
 [4 5 6]]
 
[[1 5 3 9 2 3]
 [4 7 0 4 5 6]]


In [25]:
# Flattens a 2d array to 1d

x = np.array([[1,5,3],[4,7,0]])
y = x.flatten()
print(y)

[1 5 3 4 7 0]


In [26]:
# transpose

x = np.array([[1,5,3],[4,7,0]])
print(x.shape)
print("")
x = x.T
print(x.shape)

(2, 3)

(3, 2)


In [27]:
x = np.array([[1,5],[4,7]])
inverse = np.linalg.inv(x)
print(inverse)

[[-0.53846154  0.38461538]
 [ 0.30769231 -0.07692308]]


np.add(x,y)
x + y	Addition


np.substract(x,y)
x - y	Subtraction

np.divide(x,y)
x / y	Division

np.multiply(x,y)
x @ y	Multiplication

np.sqrt(x)	Square Root

np.sin(x)	Element-wise sine

np.cos(x)	Element-wise cosine

np.log(x)	Element-wise natural log

np.dot(x,y)	Dot product

np.roots([1,0,-4])	Roots of a given polynomial coefficients

np.mean(array)	Mean

np.median(array)	Median

np.std(array)	Standard Deviation

array.sum()	Array-wise sum

array.min()	Array-wise minimum value

array.max(axis=0)	Maximum value of specified axis

array.cumsum(axis=0)	Cumulative sum of specified axis

array[i]	1d array at index i

array[i,j]	2d array at index[i][j]


array[0:3]	Select items of index 0, 1 and 2

array[0:2,1]	Select items of rows 0 and 1 at column 1

array[:1]	Select items of row 0 (equals array[0:1, :])

array[1:2, :]	Select items of row 1